/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as MainSignInRouteImport } from './routes/_main/sign-in'
import { Route as MainResetPasswordRouteImport } from './routes/_main/reset-password'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainMyFlightsIndexRouteImport } from './routes/_main/my-flights/index'
import { Route as MainAdminIndexRouteImport } from './routes/_main/admin/index'
import { Route as MainMyFlightsSearchRouteImport } from './routes/_main/my-flights/search'
import { Route as MainFlightFlightNumberRouteImport } from './routes/_main/flight.$flightNumber'
import { Route as MainAdminTracksRouteImport } from './routes/_main/admin/tracks'
import { Route as MainAdminPgbossRouteImport } from './routes/_main/admin/pgboss'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSignInRoute = MainSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainResetPasswordRoute = MainResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMyFlightsIndexRoute = MainMyFlightsIndexRouteImport.update({
  id: '/my-flights/',
  path: '/my-flights/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminIndexRoute = MainAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMyFlightsSearchRoute = MainMyFlightsSearchRouteImport.update({
  id: '/my-flights/search',
  path: '/my-flights/search',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFlightFlightNumberRoute = MainFlightFlightNumberRouteImport.update({
  id: '/flight/$flightNumber',
  path: '/flight/$flightNumber',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminTracksRoute = MainAdminTracksRouteImport.update({
  id: '/admin/tracks',
  path: '/admin/tracks',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAdminPgbossRoute = MainAdminPgbossRouteImport.update({
  id: '/admin/pgboss',
  path: '/admin/pgboss',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/about': typeof MainAboutRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/sign-in': typeof MainSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/pgboss': typeof MainAdminPgbossRoute
  '/admin/tracks': typeof MainAdminTracksRoute
  '/flight/$flightNumber': typeof MainFlightFlightNumberRoute
  '/my-flights/search': typeof MainMyFlightsSearchRoute
  '/admin/': typeof MainAdminIndexRoute
  '/my-flights/': typeof MainMyFlightsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/sign-in': typeof MainSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof MainIndexRoute
  '/admin/pgboss': typeof MainAdminPgbossRoute
  '/admin/tracks': typeof MainAdminTracksRoute
  '/flight/$flightNumber': typeof MainFlightFlightNumberRoute
  '/my-flights/search': typeof MainMyFlightsSearchRoute
  '/admin': typeof MainAdminIndexRoute
  '/my-flights': typeof MainMyFlightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/reset-password': typeof MainResetPasswordRoute
  '/_main/sign-in': typeof MainSignInRoute
  '/api/$': typeof ApiSplatRoute
  '/_main/': typeof MainIndexRoute
  '/_main/admin/pgboss': typeof MainAdminPgbossRoute
  '/_main/admin/tracks': typeof MainAdminTracksRoute
  '/_main/flight/$flightNumber': typeof MainFlightFlightNumberRoute
  '/_main/my-flights/search': typeof MainMyFlightsSearchRoute
  '/_main/admin/': typeof MainAdminIndexRoute
  '/_main/my-flights/': typeof MainMyFlightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/reset-password'
    | '/sign-in'
    | '/api/$'
    | '/admin/pgboss'
    | '/admin/tracks'
    | '/flight/$flightNumber'
    | '/my-flights/search'
    | '/admin/'
    | '/my-flights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/reset-password'
    | '/sign-in'
    | '/api/$'
    | '/'
    | '/admin/pgboss'
    | '/admin/tracks'
    | '/flight/$flightNumber'
    | '/my-flights/search'
    | '/admin'
    | '/my-flights'
  id:
    | '__root__'
    | '/_main'
    | '/_main/about'
    | '/_main/reset-password'
    | '/_main/sign-in'
    | '/api/$'
    | '/_main/'
    | '/_main/admin/pgboss'
    | '/_main/admin/tracks'
    | '/_main/flight/$flightNumber'
    | '/_main/my-flights/search'
    | '/_main/admin/'
    | '/_main/my-flights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/sign-in': {
      id: '/_main/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof MainSignInRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reset-password': {
      id: '/_main/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainResetPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/my-flights/': {
      id: '/_main/my-flights/'
      path: '/my-flights'
      fullPath: '/my-flights/'
      preLoaderRoute: typeof MainMyFlightsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/': {
      id: '/_main/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/my-flights/search': {
      id: '/_main/my-flights/search'
      path: '/my-flights/search'
      fullPath: '/my-flights/search'
      preLoaderRoute: typeof MainMyFlightsSearchRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/flight/$flightNumber': {
      id: '/_main/flight/$flightNumber'
      path: '/flight/$flightNumber'
      fullPath: '/flight/$flightNumber'
      preLoaderRoute: typeof MainFlightFlightNumberRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/tracks': {
      id: '/_main/admin/tracks'
      path: '/admin/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof MainAdminTracksRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/admin/pgboss': {
      id: '/_main/admin/pgboss'
      path: '/admin/pgboss'
      fullPath: '/admin/pgboss'
      preLoaderRoute: typeof MainAdminPgbossRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainResetPasswordRoute: typeof MainResetPasswordRoute
  MainSignInRoute: typeof MainSignInRoute
  MainIndexRoute: typeof MainIndexRoute
  MainAdminPgbossRoute: typeof MainAdminPgbossRoute
  MainAdminTracksRoute: typeof MainAdminTracksRoute
  MainFlightFlightNumberRoute: typeof MainFlightFlightNumberRoute
  MainMyFlightsSearchRoute: typeof MainMyFlightsSearchRoute
  MainAdminIndexRoute: typeof MainAdminIndexRoute
  MainMyFlightsIndexRoute: typeof MainMyFlightsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainResetPasswordRoute: MainResetPasswordRoute,
  MainSignInRoute: MainSignInRoute,
  MainIndexRoute: MainIndexRoute,
  MainAdminPgbossRoute: MainAdminPgbossRoute,
  MainAdminTracksRoute: MainAdminTracksRoute,
  MainFlightFlightNumberRoute: MainFlightFlightNumberRoute,
  MainMyFlightsSearchRoute: MainMyFlightsSearchRoute,
  MainAdminIndexRoute: MainAdminIndexRoute,
  MainMyFlightsIndexRoute: MainMyFlightsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
