/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminTracksRouteImport } from './routes/admin/tracks'
import { Route as AdminPgbossRouteImport } from './routes/admin/pgboss'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTracksRoute = AdminTracksRouteImport.update({
  id: '/admin/tracks',
  path: '/admin/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPgbossRoute = AdminPgbossRouteImport.update({
  id: '/admin/pgboss',
  path: '/admin/pgboss',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/pgboss': typeof AdminPgbossRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/pgboss': typeof AdminPgbossRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/api/$': typeof ApiSplatRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/pgboss': typeof AdminPgbossRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin/pgboss'
    | '/admin/tracks'
    | '/api/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/admin/pgboss' | '/admin/tracks' | '/api/$' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin/pgboss'
    | '/admin/tracks'
    | '/api/$'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminPgbossRoute: typeof AdminPgbossRoute
  AdminTracksRoute: typeof AdminTracksRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tracks': {
      id: '/admin/tracks'
      path: '/admin/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AdminTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pgboss': {
      id: '/admin/pgboss'
      path: '/admin/pgboss'
      fullPath: '/admin/pgboss'
      preLoaderRoute: typeof AdminPgbossRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminPgbossRoute: AdminPgbossRoute,
  AdminTracksRoute: AdminTracksRoute,
  ApiSplatRoute: ApiSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
